spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sql_execution?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      # 数据库连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活的最大时间, 默认 600000(10分钟)
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间
      max-lifetime: 1800000
      # 连接超时时间，默认30秒
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  devtools:
    add-properties: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.wgx.pojo

# 日志 (SQL打印：方法接口所在的包，不是mapper.xml所在的包)
logging:
  level:
    indi.wgx.mapper: DEBUG

#  file:
#    name: sql-log
#    path: E:\IdeaProjects\sql-execution

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
